"""add referentiel, finance et journal tables

Revision ID: 8cd5b420d279
Revises: 
Create Date: 2026-05-18 16:24:09.844459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cd5b420d279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('nb_inseres', sa.Integer(), nullable=True),
    sa.Column('nb_ignores', sa.Integer(), nullable=True),
    sa.Column('nb_total', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('debut', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestions_source'), ['source'], unique=False)

    op.create_table('communes',
    sa.Column('code_insee', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=True),
    sa.Column('code_departement', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['code_departement'], ['departements.code'], ),
    sa.PrimaryKeyConstraint('code_insee')
    )
    with op.batch_alter_table('communes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communes_code_departement'), ['code_departement'], unique=False)

    op.create_table('epci',
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('libelle', sa.String(length=300), nullable=False),
    sa.Column('type_fiscalite', sa.String(length=10), nullable=True),
    sa.Column('code_departement', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['code_departement'], ['departements.code'], ),
    sa.PrimaryKeyConstraint('siren')
    )
    with op.batch_alter_table('epci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epci_code_departement'), ['code_departement'], unique=False)

    op.create_table('deliberations_fiscalite_commune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_depcom', sa.String(length=5), nullable=False),
    sa.Column('annee', sa.SmallInteger(), nullable=False),
    sa.Column('code_departement', sa.String(length=3), nullable=True),
    sa.Column('ind_tlv', sa.Boolean(), nullable=True),
    sa.Column('taux_zrc', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('taux_zrv', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('ingere_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_departement'], ['departements.code'], ),
    sa.ForeignKeyConstraint(['code_depcom'], ['communes.code_insee'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_depcom', 'annee', name='uq_delib_fisc_com_annee')
    )
    with op.batch_alter_table('deliberations_fiscalite_commune', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliberations_fiscalite_commune_code_departement'), ['code_departement'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberations_fiscalite_commune_code_depcom'), ['code_depcom'], unique=False)

    op.create_table('deliberations_fiscalite_epci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siren_epci', sa.String(length=9), nullable=False),
    sa.Column('annee', sa.SmallInteger(), nullable=False),
    sa.Column('code_departement', sa.String(length=3), nullable=True),
    sa.Column('type_fiscalite', sa.String(length=10), nullable=True),
    sa.Column('taux_zrc', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('taux_zrv', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('ingere_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_departement'], ['departements.code'], ),
    sa.ForeignKeyConstraint(['siren_epci'], ['epci.siren'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siren_epci', 'annee', name='uq_delib_fisc_epci_annee')
    )
    with op.batch_alter_table('deliberations_fiscalite_epci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliberations_fiscalite_epci_code_departement'), ['code_departement'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliberations_fiscalite_epci_siren_epci'), ['siren_epci'], unique=False)

    op.create_table('depenses_culturelles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_insee', sa.String(length=5), nullable=False),
    sa.Column('annee', sa.SmallInteger(), nullable=False),
    sa.Column('depenses_totales_k_eur', sa.Integer(), nullable=True),
    sa.Column('depenses_fonctionnement_k_eur', sa.Integer(), nullable=True),
    sa.Column('depenses_investissement_k_eur', sa.Integer(), nullable=True),
    sa.Column('depenses_totales_eur_par_hab', sa.Integer(), nullable=True),
    sa.Column('depenses_fonctionnement_eur_par_hab', sa.Integer(), nullable=True),
    sa.Column('depenses_investissement_eur_par_hab', sa.Integer(), nullable=True),
    sa.Column('part_totale_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('part_fonctionnement_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('part_investissement_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('ingere_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_insee'], ['communes.code_insee'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_insee', 'annee', name='uq_dep_cult_commune_annee')
    )
    with op.batch_alter_table('depenses_culturelles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_depenses_culturelles_code_insee'), ['code_insee'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses_culturelles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depenses_culturelles_code_insee'))

    op.drop_table('depenses_culturelles')
    with op.batch_alter_table('deliberations_fiscalite_epci', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliberations_fiscalite_epci_siren_epci'))
        batch_op.drop_index(batch_op.f('ix_deliberations_fiscalite_epci_code_departement'))

    op.drop_table('deliberations_fiscalite_epci')
    with op.batch_alter_table('deliberations_fiscalite_commune', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliberations_fiscalite_commune_code_depcom'))
        batch_op.drop_index(batch_op.f('ix_deliberations_fiscalite_commune_code_departement'))

    op.drop_table('deliberations_fiscalite_commune')
    with op.batch_alter_table('epci', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epci_code_departement'))

    op.drop_table('epci')
    with op.batch_alter_table('communes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communes_code_departement'))

    op.drop_table('communes')
    with op.batch_alter_table('ingestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestions_source'))

    op.drop_table('ingestions')
    op.drop_table('departements')
    # ### end Alembic commands ###
